# 自动生成的 Audio 列表
# 生成时间: 2026-07-16T21:16:25
# 总计: 128 个文件

static func get_audio_paths() -> Array:
	return [
		"res:///media/0.mp3",
		"res:///media/1.mp3",
		"res:///media/2.mp3",
		"res:///media/3.mp3",
		"res:///media/logo/en.mp3",
		"res:///media/logo/logo语音1.mp3",
		"res:///media/logo/logo语音2.mp3",
		"res:///media/logo/logo语音3.mp3",
		"res:///media/logo/logo语音4.mp3",
		"res:///media/logo/logo语音5.mp3",
		"res:///media/logo/咚 小提示.mp3",
		"res:///media/不领养但带回鲨鱼/不领养，但带回鲨鱼.mp3",
		"res:///media/不领养但带回鲨鱼/我……明白了。.mp3",
		"res:///media/不领养但带回鲨鱼/谢谢你……您……谢谢您…….mp3",
		"res:///media/关灯后的BGM.mp3",
		"res:///media/关闭叉叉发现鲨鱼.mp3",
		"res:///media/喂养界面/不喂/为什么无动于衷呢？.mp3",
		"res:///media/喂养界面/不喂/其实……我提前吃了点小零食，不怎么饿，嘿嘿.mp3",
		"res:///media/喂养界面/不喂/可以帮帮我吗？.mp3",
		"res:///media/喂养界面/不喂/可以给我苹果吗？.mp3",
		"res:///media/喂养界面/不喂/唉再见了，我要出门去找食物吃了……【结局3】…….mp3",
		"res:///media/喂养界面/不喂/好饿哦…….mp3",
		"res:///media/喂养界面/不喂/好饿，要饿晕了.mp3",
		"res:///media/喂养界面/不喂/就差一点就可以吃到了.mp3",
		"res:///media/喂养界面/不喂/我闻到甜甜的香味了！.mp3",
		"res:///media/喂养界面/不喂/抱歉，如果我不是给人带来麻烦的宠物就好了.mp3",
		"res:///media/喂养界面/不喂/拜托？.mp3",
		"res:///media/喂养界面/不喂/明明苹果就在这么近的地方…….mp3",
		"res:///media/喂养界面/不喂/照料宠物让你感到很枯燥吗.mp3",
		"res:///media/喂养界面/不喂/苹果是属于你的，我没办法吃到.mp3",
		"res:///media/喂养界面/不喂/莫非……其实你讨厌我？.mp3",
		"res:///media/喂养界面/你……没什么.mp3",
		"res:///media/喂养界面/咀嚼.mp3",
		"res:///media/喂养界面/喂食/吃得很满足啦.mp3",
		"res:///media/喂养界面/喂食/啊！我怎么……完全变成方块了.mp3",
		"res:///media/喂养界面/喂食/嗝兹嗝兹_01.mp3",
		"res:///media/喂养界面/喂食/嗯？鲨鱼应该吃鱼肉？.mp3",
		"res:///media/喂养界面/喂食/好好吃哦！谢谢你！.mp3",
		"res:///media/喂养界面/喂食/好想锻炼一下消消食啊.mp3",
		"res:///media/喂养界面/喂食/已经不饿啦.mp3",
		"res:///media/喂养界面/喂食/我会不会吃胖了？.mp3",
		"res:///media/喂养界面/喂食/我爱吃苹果！.mp3",
		"res:///media/喂养界面/喂食/方形鲨鱼.mp3",
		"res:///media/喂养界面/喂食/方形鲨鱼_BGM.mp3",
		"res:///media/喂养界面/喂食/真的不能再吃了.mp3",
		"res:///media/喂养界面/喂食/糟了，好像身体卡住了.mp3",
		"res:///media/喂养界面/喂食/终于吃到了，谢谢你！.mp3",
		"res:///media/喂养界面/喂食/谢谢你愿意接纳我.mp3",
		"res:///media/喂养界面/喂食/鲨鱼吃苹果也很正常嘛.mp3",
		"res:///media/喂养界面/垃圾桶/ZZ被删.mp3",
		"res:///media/喂养界面/垃圾桶/删除音效.mp3",
		"res:///media/喂养界面/垃圾桶/啊！你把重要的东西删掉了…….mp3",
		"res:///media/喂养界面/戴上花/戴上花.mp3",
		"res:///media/喂养界面/新手引导/你好.mp3",
		"res:///media/喂养界面/新手引导/可以给我吗.mp3",
		"res:///media/喂养界面/新手引导/对对 就是那个 .mp3",
		"res:///media/喂养界面/新手引导/我想吃苹果.mp3",
		"res:///media/喂养界面/橡皮鸭子.mp3",
		"res:///media/喂养界面/睡眠/你不会一直在盯着我睡觉吧？.mp3",
		"res:///media/喂养界面/睡眠/完全睡饱啦！.mp3",
		"res:///media/喂养界面/睡眠/快睡着时突然腿抽搐一下是为什么呢？……嗯？我没有腿？.mp3",
		"res:///media/喂养界面/睡眠/我不困.mp3",
		"res:///media/喂养界面/睡眠/我刚梦见自己被吃得只剩鱼骨了，吓死我了.mp3",
		"res:///media/喂养界面/睡眠/我睡觉时有冒泡泡吗？.mp3",
		"res:///media/喂养界面/睡眠/神清气爽！.mp3",
		"res:///media/喂养界面/苹果反弹.mp3",
		"res:///media/喂养界面/锻炼/1 瘦下来咯.mp3",
		"res:///media/喂养界面/锻炼/可以让我休息吗…….mp3",
		"res:///media/喂养界面/锻炼/快离开这恶劣的主人，不然你也有危险！.mp3",
		"res:///media/喂养界面/锻炼/我…….mp3",
		"res:///media/喂养界面/锻炼/我可以去海里帮你抓鱼！.mp3",
		"res:///media/喂养界面/锻炼/我是超级肌肉鲨！.mp3",
		"res:///media/喂养界面/锻炼/我要是去游泳，算不算健身？.mp3",
		"res:///media/喂养界面/锻炼/瘦下来咯 音效.mp3",
		"res:///media/喂养界面/锻炼/累死 倒地.mp3",
		"res:///media/喂养界面/锻炼/身上有点酸疼……是正常的吗？.mp3",
		"res:///media/喂养界面/锻炼/身体有点痛，而且好困啊…….mp3",
		"res:///media/喂养界面/锻炼/这个东西是哑铃吗？.mp3",
		"res:///media/喂养界面/锻炼/鲨鱼也要健身吗？.mp3",
		"res:///media/好结局BGM.mp3",
		"res:///media/室外/你……不讨厌我吗？.mp3",
		"res:///media/室外/你明明看到我了…….mp3",
		"res:///media/室外/出门和回家音效.mp3",
		"res:///media/室外/大自然鸟叫.mp3",
		"res:///media/室外/展开信.mp3",
		"res:///media/开关灯/不妙震撼地开灯.mp3",
		"res:///media/开关灯/信号噪音.mp3",
		"res:///media/开关灯/其实……我有点怕黑， 可以开灯吗？.mp3",
		"res:///media/开关灯/呼……黑暗好吓人啊.mp3",
		"res:///media/开关灯/哇！好黑！是你关了灯吗？.mp3",
		"res:///media/开关灯/啊……终于……终于开灯了，谢谢您，请不要再这样吓我了……好可怕…….mp3",
		"res:///media/开关灯/啊……（有些惨痛）.mp3",
		"res:///media/开关灯/啊……（有些惨痛）2.mp3",
		"res:///media/开关灯/她的眼睛看到我了…….mp3",
		"res:///media/开关灯/开关灯的音效.mp3",
		"res:///media/开关灯/我害怕关灯…….mp3",
		"res:///media/开关灯/打不开灯.mp3",
		"res:///media/开关灯/拜托……可以先开个灯吗？我真的非常非常害怕关灯，要是关灯太久的话…….mp3",
		"res:///media/开关灯/求……求你了快开灯吧，是我哪里做得不好让你觉得无趣了吗，真的这么讨厌看到我吗？我……我会尽力让你开心的，可以开灯吗？.mp3",
		"res:///media/开关灯/被删除后的雪花噪音.mp3",
		"res:///media/开关灯/阶段345.mp3",
		"res:///media/普通结局BGM.mp3",
		"res:///media/最终坏结局.mp3",
		"res:///media/最终结局/一震诡异不妙的氛围声.mp3",
		"res:///media/最终结局/坏结局.mp3",
		"res:///media/最终结局/好结局.mp3",
		"res:///media/最终结局/点掉叉叉.mp3",
		"res:///media/有点悲伤结局BGM.mp3",
		"res:///media/流浪鲨鱼带回家/呼……这一次终于不用 再被 变成 电子程序了.mp3",
		"res:///media/流浪鲨鱼带回家/家里的鲨鱼：哇！新朋友！？.mp3",
		"res:///media/特殊喂养界面BGM.mp3",
		"res:///media/结局通用音效/获得结局.mp3",
		"res:///media/结局通用音效/跳转到领养询问.mp3",
		"res:///media/选语言/不要再点我啦.mp3",
		"res:///media/选语言/咚当.mp3",
		"res:///media/选语言/小鲨鱼被点击.mp3",
		"res:///media/选语言/我觉得要不选中文吧？.mp3",
		"res:///media/选语言/选了中文.mp3",
		"res:///media/选语言/选了日语.mp3",
		"res:///media/选语言/选了英语.mp3",
		"res:///media/选语言BGM.mp3",
		"res:///media/领养询问/滑走的音效.mp3",
		"res:///media/领养询问/滑走的音效2.mp3",
		"res:///media/领养询问/滑走的音效3.mp3",
		"res:///media/领养询问/滑走的音效4.mp3",
		"res:///media/领养询问/确认放弃.mp3",
		"res:///media/领养询问/确认领养.mp3",
		"res:///media/领养询问/等待40秒.mp3",
	]

static func get_audio_names() -> Array:
	var names = []
	for path in get_audio_paths():
		names.append(path.get_file().get_basename())
	return names

static func get_audio_dict() -> Dictionary:
	var dict = {}
	for path in get_audio_paths():
		dict[path.get_file().get_basename()] = path
	return dict

static func get_audio_path(name: String) -> String:
	return get_audio_dict().get(name, "")

static func exists(name: String) -> bool:
	return get_audio_dict().has(name)
